# includes
library(dplyr)
library(lubridate)
library(graphics)
library(grDevices)
# read and subset data
Sys.setlocale("LC_ALL", "English")
hpc <- read.csv2("household_power_consumption.txt", header = T, sep = ";", dec = ".")
hpc <- tbl_df(hpc)
hpc$Date <- as.character(hpc$Date)
hpc$Time <- as.character(hpc$Time)
hpc$DateTime <- with(hpc, paste(Date, Time, sep = " "))
hpc <- select(hpc, DateTime, Global_active_power, Global_reactive_power, Voltage, Global_intensity, Sub_metering_1, Sub_metering_2, Sub_metering_3, Date, Time)
twoDays <- filter(hpc, Date == "1/2/2007" | Date == "2/2/2007")
rm(hpc)
twoDays$DateTime <- strptime(twoDays$DateTime, format = "%d/%m/%Y %H:%M:%S")
twoDays <- twoDays[, 1:8]
twoDays$Global_active_power <- as.numeric(as.character(twoDays$Global_active_power))
twoDays$Global_reactive_power <- as.numeric(as.character(twoDays$Global_reactive_power))
twoDays$Voltage <- as.numeric(as.character(twoDays$Voltage))
twoDays$Global_intensity <- as.numeric(as.character(twoDays$Global_intensity))
twoDays$Sub_metering_1 <- as.numeric(as.character(twoDays$Sub_metering_1))
twoDays$Sub_metering_2 <- as.numeric(as.character(twoDays$Sub_metering_2))
# create plot
png("plot4.png", 480, 480)
par(mfcol = c(2,2))
plot(twoDays$DateTime, twoDays$Global_active_power, type = "l", ylab = "Global Active Power", xlab = "")
plot(twoDays$DateTime, twoDays$Sub_metering_1, type = "l", ylab = "Energy sub metering", xlab = "")
lines(x = twoDays$DateTime, y = twoDays$Sub_metering_2, col = "red")
lines(x = twoDays$DateTime, y = twoDays$Sub_metering_3, col = "blue")
legend("topright", lty = 1, col = c("black", "red", "blue"), legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), bty = "n" )
plot(twoDays$DateTime, twoDays$Voltage, type = "l", ylab = "Voltage", xlab = "datetime")
plot(twoDays$DateTime, twoDays$Global_reactive_power, type = "l", ylab = "Global_reactive_power", xlab = "datetime")
dev.off()
